#!/usr/bin/env python3
"""
WeSi Configuration Helper
Helps set up the environment and generate required keys.
"""
import os
import sys
from pathlib import Path


def generate_fernet_key():
    """Generate a Fernet encryption key."""
    from cryptography.fernet import Fernet
    return Fernet.generate_key().decode()


def generate_flask_secret():
    """Generate a Flask secret key."""
    import secrets
    return secrets.token_hex(32)


def check_redis():
    """Check if Redis is accessible."""
    try:
        import redis
        r = redis.Redis(host='localhost', port=6379)
        r.ping()
        return True
    except Exception:
        return False


def main():
    """Main configuration helper."""
    print("="*70)
    print("WeSi 2.0 Configuration Helper")
    print("="*70)
    print()
    
    # Check if .env exists
    env_file = Path('.env')
    if env_file.exists():
        print("⚠️  .env file already exists")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Exiting without changes")
            return
    
    print("\nGenerating configuration...\n")
    
    # Generate keys
    print("1. Generating encryption keys...")
    fernet_key = generate_fernet_key()
    flask_secret = generate_flask_secret()
    print("   ✓ Keys generated")
    
    # Get database URL
    print("\n2. Database configuration...")
    db_url = input("   Database URL [sqlite:///wesi.db]: ").strip()
    if not db_url:
        db_url = "sqlite:///wesi.db"
    print(f"   ✓ Using: {db_url}")
    
    # Get Redis URL
    print("\n3. Redis configuration...")
    redis_url = input("   Redis URL [redis://localhost:6379/0]: ").strip()
    if not redis_url:
        redis_url = "redis://localhost:6379/0"
    
    # Test Redis connection
    if redis_url == "redis://localhost:6379/0":
        if check_redis():
            print("   ✓ Redis connection successful")
        else:
            print("   ⚠️  Could not connect to Redis")
            print("   Make sure Redis is running: redis-server")
    
    # Optional: OpenAI API key
    print("\n4. Optional: OpenAI API key (for AI assistant)")
    print("   Leave blank if users will provide their own keys")
    openai_key = input("   OpenAI API key: ").strip()
    
    # Optional: Google Docs credentials
    print("\n5. Optional: Google Docs API credentials")
    print("   Leave blank to skip Google Docs integration")
    google_creds = input("   Path to service account JSON: ").strip()
    
    # Write .env file
    print("\n6. Writing configuration to .env...")
    
    env_content = f"""# WeSi Environment Configuration
# Generated by config_helper.py

# Flask Configuration
FLASK_SECRET_KEY={flask_secret}
DATABASE_URL={db_url}

# Encryption Key for API Keys
WESI_ENCRYPTION_KEY={fernet_key}

# Redis Configuration (for Celery)
REDIS_URL={redis_url}

# Optional: Server-side OpenAI API Key
"""
    
    if openai_key:
        env_content += f"OPENAI_API_KEY={openai_key}\n"
    else:
        env_content += "# OPENAI_API_KEY=sk-your-openai-api-key\n"
    
    env_content += "\n# Optional: Google Docs API Credentials\n"
    if google_creds:
        env_content += f"GOOGLE_DOCS_CREDENTIALS={google_creds}\n"
    else:
        env_content += "# GOOGLE_DOCS_CREDENTIALS=/path/to/service-account-credentials.json\n"
    
    env_content += "\n# Optional: Playwright for JS rendering\nENABLE_PLAYWRIGHT=false\n"
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("   ✓ Configuration saved to .env")
    
    # Initialize database
    print("\n7. Initializing database...")
    try:
        # Set environment variables for initialization
        os.environ['DATABASE_URL'] = db_url
        os.environ['WESI_ENCRYPTION_KEY'] = fernet_key
        
        from we_si.models import init_db
        init_db(db_url)
        print("   ✓ Database initialized")
    except Exception as e:
        print(f"   ⚠️  Database initialization failed: {e}")
        print("   You can initialize manually later with:")
        print("   python -c \"from we_si.models import init_db; init_db()\"")
    
    # Summary
    print("\n" + "="*70)
    print("Configuration Complete!")
    print("="*70)
    print("\nNext steps:")
    print("1. Install dependencies: pip install -r requirements.txt")
    print("2. Start Redis (if not running): redis-server")
    print("3. Start WeSi: ./start_wesi.sh")
    print("\nOr start services manually:")
    print("   - Celery: celery -A we_si.tasks worker --loglevel=info")
    print("   - API: python we_si/api.py")
    print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nError: {e}")
        sys.exit(1)
